### ISSUE TITLE
Cclib/Gaussian tests not passing

### ISSUE THREAD

**Issue by mazeau** [ReactionMechanismGenerator/RMG-Py#1875]
In the most recent version of rmg master, I get these gaussian/cclib errors when running tests on Discovery.  I have everything up to date with the most recent master commits.

```
======================================================================
ERROR: Test that generate_thermo_data() works correctly on gaussian PM3.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussianTest.py", line 78, in test_generate_thermo_data
    self.qmmol1.generate_thermo_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 265, in generate_qm_data
    success = self.run()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 100, in run
    return self.verify_output_file()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 170, in verify_output_file
    qm_data = self.parse()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 334, in parse
    cclib_data = parser.parse()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 363, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 412, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 203, in __init__
    self.setattributes(attributes)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 416, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 274, in setattributes
    self.arrayify()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in arrayify
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in <listcomp>
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
TypeError: float() argument must be a string or a number, not 'map'

======================================================================
ERROR: Test that generate_thermo_data() can load thermo from the previous gaussian PM3 run.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussianTest.py", line 94, in test_load_thermo_data
    self.qmmol1.generate_thermo_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 254, in generate_qm_data
    if self.verify_output_file():
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 170, in verify_output_file
    qm_data = self.parse()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 334, in parse
    cclib_data = parser.parse()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 363, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 412, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 203, in __init__
    self.setattributes(attributes)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 416, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 274, in setattributes
    self.arrayify()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in arrayify
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in <listcomp>
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
TypeError: float() argument must be a string or a number, not 'map'

======================================================================
ERROR: Test that generate_thermo_data() works correctly for gaussian PM6.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussianTest.py", line 136, in test_generate_thermo_data
    self.qmmol1.generate_thermo_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 265, in generate_qm_data
    success = self.run()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 100, in run
    return self.verify_output_file()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 170, in verify_output_file
    qm_data = self.parse()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 334, in parse
    cclib_data = parser.parse()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 363, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 412, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 203, in __init__
    self.setattributes(attributes)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 416, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 274, in setattributes
    self.arrayify()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in arrayify
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in <listcomp>
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
TypeError: float() argument must be a string or a number, not 'map'

======================================================================
ERROR: Test that generate_thermo_data() can load thermo from the previous gaussian PM6 run.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussianTest.py", line 153, in test_load_thermo_data
    self.qmmol1.generate_thermo_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 254, in generate_qm_data
    if self.verify_output_file():
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 170, in verify_output_file
    qm_data = self.parse()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 334, in parse
    cclib_data = parser.parse()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 363, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 412, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 203, in __init__
    self.setattributes(attributes)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 416, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 274, in setattributes
    self.arrayify()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in arrayify
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in <listcomp>
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
TypeError: float() argument must be a string or a number, not 'map'

======================================================================
ERROR: Test that Gaussian get_thermo_data() works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/mainTest.py", line 276, in test_get_thermo_data_gaussian
    thermo1 = self.gauss1.get_thermo_data(mol)
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/main.py", line 224, in get_thermo_data
    thermo0 = qm_molecule_calculator.generate_thermo_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 265, in generate_qm_data
    success = self.run()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 100, in run
    return self.verify_output_file()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/gaussian.py", line 170, in verify_output_file
    qm_data = self.parse()
  File "/scratch/westgroup/mazeau/Cat/RMG-Py/rmgpy/qm/molecule.py", line 334, in parse
    cclib_data = parser.parse()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 363, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 412, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 203, in __init__
    self.setattributes(attributes)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 416, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 274, in setattributes
    self.arrayify()
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in arrayify
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
  File "/home/mazeau.e/.conda/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in <listcomp>
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
TypeError: float() argument must be a string or a number, not 'map'
```

**Comment by amarkpayne** [comment]
I ran into these not too long ago. I thought I pushed a newer version of the CClib build with the fix, but I can't find this anywhere so I guess I forgot to upload it. I'll try to get on this soon, but also note that there are other bugs with QMTP right now (see #1864). Are you trying to do some work related to QMTP or is this something that you came across when running unit tests for another purpose?

**Comment by mazeau** [comment]
This is just something I came across when running unit tests

**Comment by cjmcgill** [comment]
I encountered these same test failures when running make test-all today on the master branch.

**Comment by xrulesin** [comment]
Bad Confomer ID is not catching the issue still. Gaussian still fails at the same place. Is it working at your end?
