### ISSUE TITLE
Quantum calulation problem

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#2138]
### Topic
General area which your question is related to.
 Running an RMG job

### Context
I am trying to run a simulation with quantum calculation with mopac.

### Question
I have meet Value error shown below:

```
Traceback (most recent call last):
  File "rmg.py", line 118, in <module>
    main()
  File "rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 673, in execute
    self.initialize(**kwargs)
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 496, in initialize
    self.load_database()
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 420, in load_database
    family.add_rules_from_training(thermo_database=self.database.thermo)
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/data/kinetics/family.py", line 1269, in add_rules_from_training
    reactant.thermo = thermo_database.get_thermo_data(reactant, training_set=True, metal_to_scale_to=metal)
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/data/thermo.py", line 1319, in get_thermo_data
    tdata = self.estimate_radical_thermo_via_hbi(molecule, quantum_mechanics.get_thermo_data)
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/data/thermo.py", line 2019, in estimate_radical_thermo_via_hbi
    thermo_data_sat = stable_thermo_estimator(saturated_struct)
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/qm/main.py", line 216, in get_thermo_data
    thermo0 = qm_molecule_calculator.generate_thermo_data()
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/qm/molecule.py", line 363, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/qm/mopac.py", line 302, in generate_qm_data
    self.create_geometry()
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/qm/molecule.py", line 325, in create_geometry
    self.geometry.generate_rdkit_geometries()
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/qm/molecule.py", line 135, in generate_rdkit_geometries
    self.save_coordinates_from_rdmol(rdmol, min_e_id, rdatom_idx)
  File "/home1/anguohu/anaconda3/envs/rmg_env3.1/lib/python3.7/site-packages/rmgpy/qm/molecule.py", line 173, in save_coordinates_from_rdmol
    point = rdmol.GetConformer(min_e_id).GetAtomPosition(atom.sorting_label)
ValueError: Bad Conformer Id
```

### Installation Information
Describe your installation method and system information if applicable.
 - OS (include version if known): Linux system
 - Installation method: Binary installation using anaconda
 - RMG version information: I just installed on 5/24/2021, it should be version 3.1

**Comment by rwest** [comment]
There may be other QM thermo issues, but I think this particular problem was fixed by https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2130  which is in the latest developer master (but not the 3.1 release)

**Comment by AH9316** [comment]
@rwest thank you for your response. Is that saying I can solve this problem by installing the developer version of RMG?

**Comment by rwest** [comment]
Yes, I believe so. I'd certainly try that first. It won't make QM thermo work for that species, but it'll at least keep the simulation running (with another estimate).

**Comment by AH9316** [comment]
@rwest Thank you! I will try to install the developer version also.

**Comment by AH9316** [comment]
@rwest Hi, Richard. I follow the RMG website installation steps and successfully installed developer version RMG. However, when I run the simulation with Mopac, I still get the Bad Conformed Id error. I am thinking if I installed the wrong developer version? If this is the case, how can I get the lasted developer version? Thanks!

**Comment by xrulesin** [comment]
@rwest I have installed the developer version a couple of days ago (again as a fresh install) and I am still stuck at the same error. Also true for the example cases given by RMG itself.
